name: applicants
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  sqflite: ^2.3.0
  provider: ^6.0.0
  syncfusion_flutter_charts: ^24.2.4+3
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.8.3
  intl: ^0.19.0
  table_calendar: ^3.1.1
  linalg: ^0.4.0
  bcrypt: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
